apiVersion: apps/v1
kind: Deployment
metadata:
  name: akvs-secret-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: akvs-secret-app
spec:
  selector:
    matchLabels:
      app: akvs-secret-app
  template:
    metadata:
      labels:
        app: akvs-secret-app
    spec:
      containers:
      - name: akv2k8s-env-test
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args: ["TEST_SECRET"]
        env:
        - name: TEST_SECRET
          value: "{{ .Values.akvsResourceName }}@azurekeyvault"       # name of the akvs CRD object +@azurekeyvault
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }} 