{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "azure-key-vault-to-kubernetes.serviceAccountName" . }}
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ template "azure-key-vault-to-kubernetes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end}}