{{- if .Values.addAzurePodIdentityException }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: akv2k8s-env-injector-exception
  namespace: akv2k8s # change if akv2k8s is installed in a different ns
spec:
  podLabels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    release: {{ .Release.Name }}
    component: webhook
{{- end }}
