---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-webhook-env
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.webhook.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-cabundlecontroller-env
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.caBundleController.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
