apiVersion: v1
kind: Service
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: mutating
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.externalTlsPort }}
      targetPort: {{ .Values.service.internallTlsPort }}
      protocol: TCP
    - name: {{ .Values.service.name }}-http
      port: {{ .Values.service.externalHttpPort }}
      targetPort: {{ .Values.service.internallHttpPort }}
      protocol: TCP
  selector:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    release: {{ .Release.Name }}
