addAzurePodIdentityException: false
affinity: {}
caBundleController:
  akvLabelName: azure-key-vault-env-injection
  configMapName: akv2k8s-ca
  env: {}
  image:
    pullPolicy: IfNotPresent
    repository: spvest/ca-bundle-controller
    tag: 1.1.0
  labels: {}
  logFormat: fmt
  logLevel: Info
  podLabels: {}
cloudConfigHostPath: /etc/kubernetes/azure.json
dockerImageInspection:
  timeout: 20
  useAksCredentialsWithACS: true
envImage:
  repository: spvest/azure-keyvault-env
  tag: 1.1.1
image:
  pullPolicy: IfNotPresent
  repository: spvest/azure-keyvault-webhook
  tag: 1.1.10
keyVault:
  customAuth:
    enabled: false
    useAuthService: true
metrics:
  enabled: false
nodeSelector: {}
replicaCount: 2
resources: {}
runningInsideAzureAks: true
service:
  externalHttpPort: 80
  externalTlsPort: 443
  internalHttpPort: 80
  internalTlsPort: 443
  name: azure-keyvault-secrets-webhook
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []
webhook:
  certificate:
    custom:
      ca:
        crt: null
      enabled: false
      server:
        tls:
          crt: null
          key: null
    useCertManager: false
  dockerImageInspectionTimeout: 20
  env: {}
  failurePolicy: Fail
  labels: {}
  logFormat: fmt
  logLevel: Info
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - kube-system
    matchLabels:
      azure-key-vault-env-injection: enabled
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  podLabels: {}
  securityContext:
    allowPrivilegeEscalation: true
