apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  vault:
    name: {{ required "An Azure KeyVault name is required!" .Values.keyvaultName | quote }}    # name of key vault
    object:
      name: {{ required "An Azure KeyVault Secret name is required!" .Values.keyvaultObjectName | quote }}          # name of the key vault object
      {{ if (eq .Values.keyType "mono") }}
      type: {{ .Values.keyvaultObjectType }}  # type of key vault object
      {{ else }}
      type: multi-key-value-secret            # name of the key vault type
      contentType: application/x-json         # content type in the secret
      {{ end }}
  output:
    secret:
      name: {{ .Values.k8sSecretName }} # kubernetes secret name
      {{ if (eq .Values.keyType "mono") }}
      dataKey: {{ required "A data key for the k8s secret is required!" .Values.secretKey | quote }}  # name of the key vault type
      {{ end }}